### ISSUE TITLE
Weird sheet offsetting when dragging using `isModal = false`

### ISSUE THREAD

**Issue by RoosDaniel** [skydoves/FlexibleBottomSheet#68]
**Please complete the following information:**
- **Library Version:** 0.1.5
- **Affected Device(s):** Google Pixel 8 running android 15, also appears in emulator
 
See video. When dragging the sheet with `isModal = false`, it offsets down and then goes back to expected position after it's done animating.

https://github.com/user-attachments/assets/75777671-6d83-48aa-9d47-2a00462818ae

This is the code:

```kotlin
val sheetState = rememberFlexibleBottomSheetState(
        flexibleSheetSize = FlexibleSheetSize(
            fullyExpanded = 1.0f,
            slightlyExpanded = 0.10f,
        ),
        isModal = false,
        skipHiddenState = true,
        skipSlightlyExpanded = false,
        skipIntermediatelyExpanded = true, // doesn't seem to make a difference
        containSystemBars = true,  // doesn't seem to make a difference
    )

var currentSheetStateTarget by remember {
    mutableStateOf(FlexibleSheetValue.SlightlyExpanded)
}

FlexibleBottomSheet(
        onDismissRequest = { },
        sheetState = sheetState,
        onTargetChanges = { currentSheetStateTarget = it }
    ) {
        Column(
            modifier = Modifier.fillMaxWidth(),
            horizontalAlignment = Alignment.CenterHorizontally,
        ) {}
    }
```

**Comment by RoosDaniel** [comment]
After some more investigation, it seems like this appears only for when setting `fullyExpanded = 1.0f`. Using a lower value fixes it.

**Comment by ravenfeld** [comment]
I've got the same problem, maybe it's linked to Android 15.
Even with 0.9, 
You can also see that my BottomNavigation is back in front for a while.
https://github.com/user-attachments/assets/98e9c0c9-73e1-4f10-ba75-d4e7664d3875

**Comment by ravenfeld** [comment]
I understood the problem, it is linked to the popup and to windowsmanager. I found another project which proposes another approach and by combining their solution it works.

https://github.com/oleksandrbalan/modalsheet/blob/main/modalsheet/src/main/java/eu/wewox/modalsheet/FullscreenPopup.kt

**Comment by omegamubeen** [comment]
any solution to this issue? it causing tension in my production app

**Comment by skydoves** [comment]
Hi everyone, a new version 0.2.0 has been released, and this should be fixed.

**Comment by rexmtorres** [comment]
I still encounter the issue in v0.2.0.  My setup is a bit different though.  I needed to add some padding at the bottom so that the bottom sheet will not cover the tabs at the bottom of my main screen.  See `modifier` in the code below.

```kotlin
FlexibleBottomSheet(
    onDismissRequest = {},
    sheetState = sheetState,
    modifier = Modifier.padding(
        bottom = bottomTabBarHeight
    )
) {
    BottomSheetContent(
        quickLinks = quickLinks,
        favoriteDoorsList = favoriteDoorsList,
        ...
    )
}
```

<img width="480" height="743" alt="Image" src="https://github.com/user-attachments/assets/c74ad67b-1f2b-40a2-b854-3aec7b2fdedc" />
